### ISSUE TITLE
Issue in BlockBuilder example when using a different block scale

### ISSUE THREAD

**Issue by rvandoosselaer** [rvandoosselaer/Blocks#12]
Will appreciate if you can also update the BlockBuilder example to work with different block scales. When setting block scale other than 1 editor does not behave as expected.

Edit:
I guess these methods in ChunkManager :

getChunkLocation()
getBlockLocation()
getNeighbourBlockLocation()
addBlock()
removeBlock()
need to take the block scale into account when finding chunk/block location Vec3i? :thinking:

See [forum post](https://hub.jmonkeyengine.org/t/blocks/42465/25).

**Comment by Ali-RS** [comment]
Note, the changes in `addBlock()` and `removeBlock()` methods in `BlockBuilder.java` class are not needed, no need to divide WorldTranslation by block scale. https://github.com/rvandoosselaer/Blocks/pull/13#discussion_r361679414
