### ISSUE TITLE
Chunk should have a public constructor so that it supports inheritance

### ISSUE THREAD

**Issue by Sam54123** [rvandoosselaer/Blocks#48]
In my project, I'm trying to resolve a compatibility issue between two systems, and the best way I can think to do this was by making a child class of `Chunk`, but I can't because it has a private constructor.

I don't understand why it has to have a private constructor though, because you could just make the constructor have all the code from `createAt` and re-write `createAt` to just feed the location into the constructor for backward compatibility.

So why don't you do that?

**Comment by rvandoosselaer** [comment]
Hi Sam,

the reason to not have a pubic constructor with the location is for readability purposes. `Chunk.createAt(new Vec3i(0, 0, 0));` describes better the function/goal of the passed vector parameter then `new Chunk(new Vec3i(0, 0, 0));`.

The downside of this is that it doesn't support inheritance. I'll create a hotfix PR for this on the last stable release.

**Comment by rvandoosselaer** [comment]
Feature available in release [v1.5.1](https://github.com/rvandoosselaer/Blocks/releases/tag/v1.5.1)

**Comment by Sam54123** [comment]
Thanks!
