### ISSUE TITLE
All the blocks in a Chunk become the placed block

### ISSUE THREAD

**Issue by fierceeo** [rvandoosselaer/Blocks#57]
When placing a block in a chunk that is different then all the current blocks in that chunk, all the blocks in that chunk will become the block that you placed.

Screenshot:
![image](https://user-images.githubusercontent.com/48343703/99162814-df77b600-26b6-11eb-98c8-aa512df9719e.png)

Note:
I am placing blocks using this code:
        Block myBlock = blockRegistry.get(BlockIds.GRASS);
        myBlock.setShape(ShapeIds.POLE);
        chunkManager.addBlock(blockLocation.subtract(0.5f, 0.5f, 0.5f), myBlock)

I am using blocks version: 1.6.3
and minie version: 3.0.0+debug

**Comment by rvandoosselaer** [comment]
Hi, this is actually normal behaviour. What your code is doing, is changing the shape of all GRASS blocks from a cube to a pole.

What you probably want to do, is create a new block with a grass type and the shape of a pole.

```java
Block customBlock = Block.builder()
                .name(BlockIds.getName(TypeIds.GRASS, ShapeIds.POLE))
                .shape(ShapeIds.POLE)
                .type(TypeIds.GRASS)
                .solid(true)
                .transparent(false)
                .usingMultipleImages(true)
                .build();
BlockRegistry blockRegistry = BlocksConfig.getInstance().getBlockRegistry();
blockRegistry.register(customBlock);
```

Now you can place this block wherever you want:

```java
chunkManager.addBlock(blockLocation.subtract(0.5f, 0.5f, 0.5f), customBlock);
```

**Comment by fierceeo** [comment]
Thanks for the info and the explanation, that solved my issue :)
