### ISSUE TITLE
Not working on Windows (Build and prebuild)

### ISSUE THREAD

**Issue by Coronon** [rvandoosselaer/Blocks#6]
Hi there,
I am trying to use this library in my project and all works fine on my Mac, but as soon as I try to run it on windows I get an `com.jme3.asset.AssetNotFoundException` exception(both with the version I build on windows and the one I build on my mac). Trying to build Blocks with gradle also fails, here is the log:
```

gradle build

> Task :test FAILED

com.rvandoosselaer.blocks.BlocksConfigTest > initializationError FAILED
    com.jme3.asset.AssetNotFoundException at BlocksConfigTest.java:16

com.rvandoosselaer.blocks.BlocksManagerTest > initializationError FAILED
    com.jme3.asset.AssetNotFoundException at BlocksManagerTest.java:17

com.rvandoosselaer.blocks.ChunkTest > initializationError FAILED
    com.jme3.asset.AssetNotFoundException at ChunkTest.java:14

com.rvandoosselaer.blocks.FacesMeshGeneratorTest > initializationError FAILED
    com.jme3.asset.AssetNotFoundException at FacesMeshGeneratorTest.java:23

com.rvandoosselaer.blocks.FileRepositoryTest > initializationError FAILED
    com.jme3.asset.AssetNotFoundException at FileRepositoryTest.java:23

14 tests completed, 5 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/?/Desktop/Blocks-1.1.0/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
5 actionable tasks: 5 executed
```

Thanks for this awesome project nonetheless dude :)

**Comment by rvandoosselaer** [comment]
Hi, could you send met the stacktrace of the error?
I'll try to investigate your issue.

**Comment by Coronon** [comment]
After looking further into this it seems to boil down to this:
```
com.jme3.asset.AssetNotFoundException: Asset name doesn't match requirements.
"C:/Users/?/Desktop/Blocks-1.1.0/build/resources/main/Blocks/Themes/default/birch_log.png" doesn't match "Blocks\Themes\default\birch_log.png"
```

**Comment by Coronon** [comment]
I just tried using gradel but I get exactly the same error :/
`AssetNotFoundException: Texture Blocks\Themes\default\grass.png not found!`

**Comment by rvandoosselaer** [comment]
Thanks for the input. I’ll take a closer look at it and come back to you!

**Comment by rvandoosselaer** [comment]
I was able to reproduce and fix the bug you where encountering: b659d7658bf47054457ddc858379c4fcb6e1f306

I'll release a new version with this bugfix in later this evening.

Thanks for reporting it!

**Comment by Coronon** [comment]
I has to do with the windows filesystem, I fixed my first errors now, only thing left are FileRepositoryTest errors, which have to do with permission being denied to write the chunk:
`java.nio.file.AccessDeniedException: C:\Users\?\.blocks\repository\chunk_0_0_0.block`

**Comment by rvandoosselaer** [comment]
> I has to do with the windows filesystem, I fixed my first errors now, only thing left are FileRepositoryTest errors, which have to do with permission being denied to write the chunk:
> `java.nio.file.AccessDeniedException: C:\Users\?\.blocks\repository\chunk_0_0_0.block`
> 
> Will submit a pull request once completely done

The tests that are causing the `java.nio.file.AccessDeniedException` are also fixed on master and will be included in the bugfix release.

**Comment by rvandoosselaer** [comment]
Version v1.1.1 is released and pushed to bintray.
