### ISSUE TITLE
Both package services have shut down

### ISSUE THREAD

**Issue by leha-code** [rvandoosselaer/Blocks#65]
There is no way to download the module as a dependency

**Comment by rvandoosselaer** [comment]
Unfortunately bintray and jcenter both shutdown.

However, you can always include the module as a local dependency.
You can include `mavenLocal()` in your repository section of the build file. Checkout the Blocks sources and use the `maven-publish` plugin to build and install Blocks into your local maven repository.

See the gradle [user doc](https://docs.gradle.org/current/userguide/publishing_maven.html) for more info.
