### ISSUE TITLE
Blocks dont create a plane

### ISSUE THREAD

**Issue by Coronon** [rvandoosselaer/Blocks#7]
Hi, after my first issue and your really fast help I would like to raise another issue.
If I create a plane of blocks (100x100) and walk over it my y position changes ever so slightly while I move, creating very weird effects, is it me, or are the blocks not perfectly level? We are talking 0.01-0.02 Δy.

Adding to this, there is also a very visible cut between blocks one one axis (I think its along the x axis)

Thanks for your help again :)

**Comment by rvandoosselaer** [comment]
Can you create a test case to reproduce this behaviour?

**Comment by Coronon** [comment]
I can send you my code If you want, as the physics and all that are important

**Comment by Coronon** [comment]
[Coronon-Blocks.zip](https://github.com/rvandoosselaer/Blocks/files/3935143/Coronon-Blocks.zip)

The 'Score' shows the current camera y position, just walk forward and you will notice what I mean :)

**Comment by rvandoosselaer** [comment]
Hi, I took a look at your code.

The gap you are describing between the blocks, is not really a gap. It's the grass texture that makes it look like it's a gap.
The grass texture:
![grass](https://user-images.githubusercontent.com/11334424/70381632-f44bb580-194d-11ea-9600-b64ebddeb2de.png)

I'll create a better grass texture in the next release of Blocks. To fix this for now, you can pick a different texture and use this as the grass texture.

Concerning the head bobbing you encounter, this is actually an issue with the physics engine (bullet). The mesh that Blocks generate is smooth. You could try to fine-tune some settings of bullet to counter this behaviour.
You can find documentation [here](https://wiki.jmonkeyengine.org/jme3/advanced/physics.html#best-practices) and you can always check out the [forum](https://hub.jmonkeyengine.org)
Try to enable the debug mode of bullet so you can see what's happening in the physics simulation.

**Comment by Coronon** [comment]
Hi, thanks for your support, Im new to JME so I don't know a lot about JBullet. I am nor really able to see how I can tweak some settings to make my game run smoother, even after having a look at the docs. I don't expect you to help me with any unrelated questions, so please feel free to close this :) But are there any alternatives to bullet then?

**Comment by Coronon** [comment]
Found some settings that make it work way better, thanks man :)

**Comment by rvandoosselaer** [comment]
Glad you got it working!
